# Generated by Django 5.1.4 on 2024-12-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_payment_payment_link_payment_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateField(blank=True, help_text="Введите дату оплаты", null=True, verbose_name="Дата оплаты"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[("Наличные", "Наличные"), ("Безналичный перевод", "Безналичный перевод")],
                help_text="Выберите способ платежа",
                max_length=50,
                null=True,
                verbose_name="Способ платежа",
            ),
        ),
    ]
