# Generated by Django 5.1.4 on 2024-12-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(help_text="Введите название курса", max_length=100, verbose_name="Название курса"),
        ),
    ]
