# Generated by Django 5.1.4 on 2024-12-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_alter_lesson_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(
                help_text="Введите название курса", max_length=100, unique=True, verbose_name="Название курса"
            ),
        ),
    ]
